export const bookdata = [
  {
    id: 2,
    bookname: "અક્ષરજ્ઞાન - ગુજરાતી મૂળાક્ષર લેખન અભ્યાસ",
    description: [
      "(1) મૂળાક્ષર પર ઘૂંટવાની પ્રેક્ટિસ",
      "(2) ચિત્રો દ્વારા મૂળાક્ષરની ઓળખ",
      "(3) વિવિધ આકારો પર ઘૂંટવાનો અભ્યાસ ",
      "(4) મૂળાક્ષરો ઓળખવાનો અભ્યાસ ",
      "(5) દર ૫/૬ મૂળાક્ષરો પછી આગળ શીખેલા મૂળાક્ષરોનો અભ્યાસ",
      "(6) છેલ્લે દરેક મૂળાક્ષરોની વિડિયો દ્વારા સમજૂતી તો ખરી જ.",
      // "(1)earning to kneel on the alphabet",
      // "(2)Recognition of alphabets through pictures",
      // "(3)Alphabet recognition through active practice",
      // "(4)Learned alphabet activity",
      // "(4)Explanation through video",
    ],
    rating: 4.5,
    review: 1526,
    price: 120,
    image: [
      "/Barkadi/Barkadi.jpg",
      "/Barkadi/Barkadi (1).jpg",
      "/Barkadi/Barkadi (2).jpg",
      "/Barkadi/Barkadi (7).jpg",
    ],
    slug: "Gujarati-and-English-Letter-writing",
  },
  {
    id: 1,
    bookname: "The King Kong - માસ્ટર દેશી હિસાબ",
    // bookname: "કિંગ કૉંગ ધ માસ્ટર દેશી હિસાબ King Kong The Master Desi Hisab",
    description: [
      "(1) Live explanation through video.",
      "(2) Inclusion of more than 100 points.",
      "(3) Inclusion of general knowledge.",
      "(4) More than 2000 English word fund.",
      "(5) Covering Basic English Grammar.",
      "(6) Useful for English speaking.",
      "(7) Books in Gujarati, Hindi and English languages.",
      "(8) Useful in class 1 to 8.",
      "(9) Color book of 80 pages.",
      "(10) Explanation of each point by example",
    ],
    rating: 4.5,
    review: 2985,
    price: 120,
    image: ["/Desihisab.jpg", "/Barkadi.jpg", "/ABCD.jpg"],
    slug: "King-Kong-The-Master-Desi-Hisab",
  },
  {
    id: 3,
    bookname: " અંગ્રેજી અલ્ફાબેટ કેપિટલ અને સ્મોલ લેટર",
    // bookname: " અક્ષરજ્ઞાન - Letter Tracing and Hand Writing Practice",
    description: [
      '(1) અંગ્રેજી આલ્ફાબેટ પર ઘૂંટવાની પ્રેક્ટિસ',
      '(2) અંગ્રેજી આલ્ફાબેટ ઓળખવાનો અભ્યાસ ',
      '(3) વિવિધ આકારો પર ઘૂંટવાનો અભ્યાસ ',
      '(4) ચિત્રો દ્વારા અંગ્રેજી આલ્ફાબેટની ઓળખ',
      '(5) દર ૫/૬ આલ્ફાબેટ પછી આગળ શીખેલા આલ્ફાબેટનો અભ્યાસ',
      '(6) છેલ્લે દરેક abcd નો વિડિયો દ્વારા સમજૂતી તો ખરી જ.',



      // "(1)A study of kneeling on different shape",
      // "(2)Identifying English alphabets through pictures",
      // "(3)Study of kneeling on ABCD",
      // "(4)Practice the learned alphabet",
      // "(5)Learning the alphabet through active learning",
      // "(6) Understand Letter Tracing through the Video",
    ],
    rating: 4.5,
    review: 1687,
    price: 120,
    image: [
      "/EnglishLetter/EnglishLetter (1).jpg",
      "/EnglishLetter/EnglishLetter (2).jpg",
      "/EnglishLetter/EnglishLetter (3).jpg",
      "/EnglishLetter/EnglishLetter (10).jpg",
    ],
    slug: "Letter-Tracing-and-Hand-Writing-Practice",
  },
  {
    id: 4,
    bookname: "અંકજ્ઞાન ૧ થી ૫૦ લેખન-અભ્યાસ પુસ્તક (ગુજરાતી- અંગ્રેજી)",
    description: [
      "(1) વિવિધ આકારો પર ઘૂંટવાનો અભ્યાસ ",
      "(2) ચિત્રો દ્વારા અંકોની ગણતરી ",
      "(3) અંકો પર ઘૂંટવાનો અભ્યાસ",
      "(4) અંકોને ઓળખવાનો અભ્યાસ ",
      "(5) દર દસ અંક પછી આગળ શીખેલા અંકોનો અભ્યાસ",
      "(6) છેલ્લે દરેક અંકોની વિડિયો દ્વારા સમજૂતી તો ખરી જ..",

      // "Study of kneading on different shapes",
      // "Study of Gujarati-English numerals",
      // "Counting digits through pictures",
      // "Active study for self-study",
      // "Explanation of numbers through video",
    ],
    rating: 4.5,
    review: 1259,
    price: 120,
    image: [
      "/Maths/Maths (1).jpg",
      "/Maths/Maths (4).jpg",
      "/Maths/Maths (9).jpg",
      "/Maths/Maths (8).jpg",
    ],
    slug: "ankgyan",
  },
];
